
<!DOCTYPE html>
<html>
<head>
  <title>Employee Directory</title>
  <link rel="stylesheet" href="styles.css" />
</head>

<body>
  <div>
  <h1>Employee Directory</h1></div>
  <div>
  <input type="text" id="searchInput" placeholder="Search by name or email" />
</div>

  <button onclick="openForm()">Add Employee</button>

  <div id="filters">
    <select id="departmentFilter"><option value="">All Departments</option></select>
    <select id="roleFilter"><option value="">All Roles</option></select>
    <select id="sortBy">
      <option value="">Sort By</option>
      <option value="firstName">First Name</option>
      <option value="department">Department</option>
    </select>
  </div>

  <div id="employeeList"></div>

  <script src="data.js"></script>
  <script src="script.js"></script>
 
</body>
</html>
